name: snowflake-schemachange-demo

on:
  push:
    paths:
      - 'migrations/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: save private-key to file
        env:
          SF_PRIVATE_KEY: ${{ secrets.SF_PRIVATE_KEY }}
        run: |
            echo $SF_PRIVATE_KEY >> /tmp/sf_key

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: "SCHAMACHANGE_DEMO"
          SNOWFLAKE_PRIVATE_KEY_PATH: "/tmp/sf_key"
          SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SF_PRIVATE_KEY_PASS }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange \
          -f "$GITHUB_WORKSPACE"/migrations \
          -a "$SF_ACCOUNT" \
          -u "$SF_USERNAME" \
          -r "$SF_ROLE" \
          -w "$SF_WAREHOUSE" \
          -d "$SF_DATABASE" \
          -c "$SF_DATABASE".PUBLIC.CHANGE_HISTORY;
